env:
  SEGMENT_CONTEXTS: "snyk,npm,aws-credentials,ecr"
steps:
  - label: ":hammer: Build Dev Dependencies"
    command:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - make install
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'package-lock.json' }}"
          paths: ["node_modules/"]
      - docker#v3.3.0:
          image: node:10.16.3
          environment:
            - NPM_TOKEN

  - wait: ~

  - label: ":clippy: Test"
    commands:
      - make test
      - yarn codecov
    artifact_paths:
      - "coverage/**/*"
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-dev-{{ checksum 'package-lock.json' }}"
          paths: ["node_modules/"]
      - docker#v3.3.0:
          image: node:10.16.3

  - label: ":lock: Check Prod Dependencies"
    command:
      - npm config set "//registry.npmjs.org/:_authToken" $${NPM_TOKEN}
      - npm ci
      - node -e "require('./dist/boot'); process.exit(0)"
    plugins:
      - ssh://git@github.com/segmentio/cache-buildkite-plugin#v1.0.0:
          key: "v1-cache-prod-{{ checksum 'package-lock.json' }}"
          paths: ["node_modules/"]
      - ssh://git@github.com/segmentio/snyk-buildkite-plugin#v1.0.0:
          runtime: npm
      - docker#v3.3.0:
          image: node:10.16.3
          environment:
            - NPM_TOKEN

  - wait: ~

  - label: ":rocket: Publish"
    branches: master
    command: yarn run publish
